#!/bin/bash

# Get the current keyboard layout and variant
current_layout=$(setxkbmap -query | grep layout | awk '{print $2}')
current_variant=$(setxkbmap -query | grep variant | awk '{print $2}')

# Logic for toggling between layouts
if [[ "$current_layout" == "qwerty-seine" ]]; then
    # Switch to by(legacy)
    setxkbmap by -variant legacy
elif [[ "$current_layout" == "by" && "$current_variant" == "legacy" ]]; then
    # Switch to pl(legacy)
    setxkbmap qwerty-seine
else
    # Default to pl(legacy) if neither is set
    setxkbmap qwerty-seine
fi

kill -38 $(pidof dwmblocks)

