#!/bin/bash

#
# This will be a script for choosing output screen
# Probably I should to add option for choosing output (ex. DP-1 or DP-2)
#
# Choose what to do:
#
#   1. extend
#       1. DP-1
#       2. VGA-1
#       3. DP-2
#       4. VGA-2
#
#   2. redirect output
#       1. DP-1
#       2. VGA-1
#       3. DP-2
#       4. VGA-2
#
#   3. duplicate
#

dmenu_font="$1"
nb="$2"
nf="$3"
sb="$4"
sf="$5"
update_wallpaper=1

choice=$(echo -e "Reset\nExtend\nRedirect\nDuplicate" | dmenu -fn "$dmenu_font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -p "Select an action:")

case "$choice" in
    "Reset")
        xrandr --auto
        sleep "$update_wallpaper"
        feh --bg-fill "$WALLPAPER_PATH";;

    "Extend")
        output=$(echo -e "HDMI-1\nDP-1\nVGA-1\nDP-2\nVGA-2" | dmenu  -fn "$dmenu_font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -p "Choose output:")
        xrandr --auto
        xrandr --output "$output" --preferred --right-of "$MAIN_MONITOR"
        sleep "$update_wallpaper"
        feh --bg-fill "$WALLPAPER_PATH";;

    "Redirect")
        output=$(echo -e "HDMI-1\nDP-1\nVGA-1\nDP-2\nVGA-2" | dmenu -fn "$dmenu_font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -p "Choose output:")
        xrandr --output "$output" --preferred 
        xrandr --output "$MAIN_MONITOR" --off
        sleep "$update_wallpaper"
        feh --bg-fill "$WALLPAPER_PATH";;

    "Duplicate")
        output=$(echo -e "HDMI-1\nDP-1\nVGA-1\nDP-2\nVGA-2" | dmenu -fn "$dmenu_font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -p "Choose output:")
        xrandr --output "$MAIN_MONITOR" --mode 1920x1080
        xrandr --output "$output" --mode 1920x1080 --same-as "$MAIN_MONITOR"
        sleep "$update_wallpaper"
        feh --bg-fill "$WALLPAPER_PATH";;

    esac

