#!/usr/bin/env bash


default_out="DisplayPort-1"
grep_device=" pen "


echo "Available input devices:"
xinput list
echo


auto_id=$(xinput list | grep -i "$grep_device" | grep -oE "id=[0-9]+" | grep -oE "[0-9]+" | head -n1)
if [[ $auto_id == "" ]]; then
	auto_id="nill"
fi


read -rp "Enter the device ID for your pen (Auto: $auto_id): " pen_id
if [[ $pen_id == "" ]]; then
	pen_id="$auto_id"
fi


echo
echo "Available screens:"
xrandr | grep " connected"
echo


auto_out=$(xrandr | grep " connected"  | grep -o "$default_out" | head -n1)
if [[ $auto_out == "" ]]; then
	auto_out="nill"
fi


read -rp "Enter the screen output to map the tablet to (Auto: $auto_out): " monitor_out
if [[ $monitor_out == "" ]]; then
	monitor_out="$auto_out"
fi


if [[ $pen_id == "nill" || $monitor_out == "nill" ]]; then
	echo "Nill encountered: pen_id=$pen_id, monitor_out=$monitor_out"
	exit 1
fi


xinput map-to-output "$pen_id" "$monitor_out"
echo "Pen is mapped to $monitor_out"

