#!/usr/bin/env bash

# deployes config
deploy ()
{
	echo 'Deploying dwm configs'
	cp -rf ./dot_bash_profile $HOME/.bash_profile
	cp -rf ./dot_bashrc       $HOME/.bashrc
	cp -rf ./dot_xinitrc      $HOME/.xinitrc

	mkdir -p $HOME/.config
	cp -rf ./dot_config/* $HOME/.config/

	mkdir -p $HOME/.fonts
	cp -rf ./dot_fonts/* $HOME/.fonts/

	echo 'installing dwm'
	sudo make -C "$HOME/.config/suckless/dwm" clean install
	echo 'installing dwmblocks'
	sudo make -C "$HOME/.config/suckless/dwmblocks" clean install

	echo 'All done'
}

# collects all config updates
collect ()
{
	echo 'Copying dwm configs'
	cp -rf $HOME/.bash_profile ./dot_bash_profile
	cp -rf $HOME/.bashrc       ./dot_bashrc
	cp -rf $HOME/.xinitrc      ./dot_xinitrc
	cp -rf $HOME/.fonts/*      ./dot_fonts/
	# configs
	cp -rf $HOME/.config/betterlockscreen ./dot_config/betterlockscreen/
	cp -rf $HOME/.config/dunst            ./dot_config/
	cp -rf $HOME/.config/fastfetch        ./dot_config/
	cp -rf $HOME/.config/kitty            ./dot_config/
	cp -rf $HOME/.config/kritarc          ./dot_config/
	cp -rf $HOME/.config/mimeapps.list    ./dot_config/
	cp -rf $HOME/.config/mpv              ./dot_config/
	cp -rf $HOME/.config/picom            ./dot_config/
	cp -rf $HOME/.config/suckless         ./dot_config/
	cp -rf $HOME/.config/wallpapers       ./dot_config/
	cp -rf $HOME/.config/xkb              ./dot_config/
	cp -rf $HOME/.config/zathura          ./dot_config/
	echo 'All done'
}

case "$1" in
	deploy) deploy
	;;
	collect) collect
	;;
	*) echo 'Usage: autoconf deploy|collect'
	;;
esac


