#!/bin/sh

WALLPAPER_PATH="$HOME/.config/suckless/images/wallpaper/Touhou_Project/suika.jpg"

# Start applications on startup
feh --bg-fill "$WALLPAPER_PATH" &
betterlockscreen -u "$WALLPAPER_PATH" --fx dimblur &
dwmblocks &
picom &
nm-applet &
dunst &
#redshift -t 5700:1000 -l 51:17 & #Latitude:Longitute of Wroclaw | Uncomment for automatic

# Initial settings
setxkbmap pl -variant legacy
xrandr --output eDP-1 --mode 1920x1080  --rate 60	# x220
#xrandr --output DP-4 --mode 1920x1080 --rate 144 	# PC

# Turn off screen functions OFF
xset s off
xset -dpms

# File picker not opening fix
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start dwm
exec dwm

