#!/bin/bash

## pipewire
vol_info=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
vol=$(echo "$vol_info" | awk '{print $2*100}' | awk '{printf "%.0f", $1}')
mute_status=$(echo "$vol_info" | grep -o 'MUTED')

if [ -n "$mute_status" ]; then
    echo "消音 ${vol}"
else
    echo "音量 ${vol}"
fi

