#!/bin/bash

choice=$(echo -e "pl(legacy)\nby(legacy)\nby(latin)" | dmenu -fn 'IBM 3270:size=10' -nb '#111111' -nf '#777777' -sb '#004444' -sf '#cccccc' -p "Select an action:")

case "$choice" in
    "pl(legacy)") setxkbmap pl -variant legacy ;;
    "by(legacy)") setxkbmap by -variant legacy ;;
    "by(latin)") setxkbmap by -variant latin ;;
esac

kill -38 $(pidof dwmblocks)

