#!/bin/bash

choice=$(echo -e "pl(legacy)\nby(legacy)\nby(latin)" | dmenu -fn 'IBM 3270:size=10:bold' -nb '#111111' -nf '#ffffff' -sb '#4d0000' -sf '#ffffff' -p "Select an action:")

case "$choice" in
    "pl(legacy)") setxkbmap pl -variant legacy ;;
    "by(legacy)") setxkbmap by -variant legacy ;;
    "by(latin)") setxkbmap by -variant latin ;;
esac

kill -38 $(pidof dwmblocks)

