#!/bin/bash

## pipewire
vol_info=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
vol=$(echo "$vol_info" | awk '{print $2*100}' | awk '{printf "%.0f", $1}')
mute_status=$(echo "$vol_info" | grep -o 'MUTED')

if [ -n "$mute_status" ]; then
    echo "VolX${vol}%"
else
    echo "Vol ${vol}%"
fi

## pulseaudio
#vol_info="$(amixer get Master | tail -n1)"
#vol="$(echo "$vol_info" | sed -r 's/.*\[(.*)%\].*/\1/')"
#mute_status="$(echo "$vol_info" | grep -o '\[off\]')"
#
#if [ -n "$mute_status" ]; then
#    echo "VolX${vol}%"
#else
#    echo "Vol ${vol}%"
#fi
