#!/bin/bash

choice=$(echo -e "PL(Legacy)\nBY(Legacy)\nBY(Latin)" | dmenu -fn 'IBM 3270:size=10' -nb '#111111' -nf '#777777' -sb '#004444' -sf '#cccccc' -p "Select an action:")

case "$choice" in
    "PL(Legacy)") setxkbmap pl -variant legacy ;;
    "BY(Legacy)") setxkbmap by -variant legacy ;;
    "BY(Latin)") setxkbmap by -variant latin ;;
esac

