#!/bin/bash

#
# This will be a script for choosing output screen
# Probably I should to add option for choosing output (ex. DP-1 or DP-2)
#
# Choose what to do:
#
#   1. extend
#       1. DP-1
#       2. VGA-1
#       3. DP-2
#       4. VGA-2
#
#   2. redirect output
#       1. DP-1
#       2. VGA-1
#       3. DP-2
#       4. VGA-2
#
#   3. duplicate
#

choice=$(echo -e "Reset\nExtend\nRedirect\nDuplicate" | dmenu -b -fn 'IBM 3270:size=10:bold' -nb '#222222' -nf '#ffffe6' -sb '#ffffe6' -sf '#111111' -p "Select an action:")

case "$choice" in
    "Reset")
        xrandr --auto
	sleep 5
        feh --bg-fill /home/bk/.config/my_system_things/my_system_photos/Wallpaper/NieR_Theme/OrchestralArrangementAlbumCover.webp;;

    "Extend") 
        output=$(echo -e "DP-1\nVGA-1\nDP-2\nVGA-2" | dmenu -b -fn 'IBM 3270:size=10:bold' -nb '#222222' -nf '#ffffe6' -sb '#ffffe6' -sf '#111111' -p "Choose output:")
        xrandr --auto
        xrandr --output "$output" --preferred --left-of LVDS-1
	sleep 5
        feh --bg-fill /home/bk/.config/my_system_things/my_system_photos/Wallpaper/NieR_Theme/OrchestralArrangementAlbumCover.webp;;
        
    "Redirect")
        output=$(echo -e "DP-1\nVGA-1\nDP-2\nVGA-2" | dmenu -b -fn 'IBM 3270:size=10:bold' -nb '#222222' -nf '#ffffe6' -sb '#ffffe6' -sf '#111111' -p "Choose output:")
        xrandr --output "$output" --preferred 
        xrandr --output LVDS-1 --off
	sleep 5
        feh --bg-fill /home/bk/.config/my_system_things/my_system_photos/Wallpaper/NieR_Theme/OrchestralArrangementAlbumCover.webp;;
    
    "Duplicate")
        output=$(echo -e "DP-1\nVGA-1\nDP-2\nVGA-2" | dmenu -b -fn 'IBM 3270:size=10:bold' -nb '#222222' -nf '#ffffe6' -sb '#ffffe6' -sf '#111111' -p "Choose output:")
        xrandr --output LVDS-1 --mode 1280x720
        xrandr --output "$output" --mode 1280x720 --same-as LVDS-1
	sleep 5
        feh --bg-fill /home/bk/.config/my_system_things/my_system_photos/Wallpaper/NieR_Theme/OrchestralArrangementAlbumCover.webp;;
        
esac

