#!/bin/bash

choice=$(echo -e "pl(legacy)\nby(legacy)\nby(latin)" | dmenu -b -fn 'IBM 3270:size=10:bold' -nb '#222222' -nf '#ffffe6' -sb '#ffffe6' -sf '#111111' -p "Select an action:")

case "$choice" in
    "pl(legacy)") setxkbmap pl -variant legacy ;;
    "by(legacy)") setxkbmap by -variant legacy ;;
    "by(latin)") setxkbmap by -variant latin ;;
esac

kill -38 $(pidof dwmblocks)
