#!/bin/bash

choice=$(echo -e "Shutdown\nReboot\nLogout" | dmenu -b -fn 'IBM 3270:size=10:bold' -nb '#222222' -nf '#ffffe6' -sb '#ffffe6' -sf '#111111' -p "Select an action:")

case "$choice" in
    "Shutdown") systemctl poweroff ;;
    "Reboot") systemctl reboot ;;
    "Logout") loginctl terminate-user $USER ;;
esac

