#!/bin/bash

vol_info="$(amixer get Master | tail -n1)"
vol="$(echo "$vol_info" | sed -r 's/.*\[(.*)%\].*/\1/')"
mute_status="$(echo "$vol_info" | grep -o '\[off\]')"

if [ -n "$mute_status" ]; then
    echo "VolX${vol}%"
else
    echo "Vol ${vol}%"
fi
